### PR TITLE
Mod Archive post Nexus removals

### PR DESCRIPTION
**Pull request by PrimeSonic**
> This page exists to archive my mods as they were on Nexus by August 5th.
> See also [Release Aug5_2021](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/releases/tag/Aug5_2021)

# Subnautica Mods by PrimeSonic
[AIOFabricator.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927034/AIOFabricator.zip)
`All-in-One Fabricator (SN1)` Makes a new fabricator that is every single fabricator combined together.
Automatically includes modded items and mod created fabricator.

[BetterBioReactor.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927035/BetterBioReactor.zip)
`Better BioReactor (SN1)` Makes the bio reactor in game also show the amount of charge each item has left.
Makes items process in parallel instead of sequentially.

[CyclopsAutoZapper.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927036/CyclopsAutoZapper.zip)
`Cyclops Auto Zapper (SN1)` Two tiers of autozapper, the first tier requires a seamoth in the docking bay that has that shock module installed and the cyclops will automatically shock enemies that attack.
Second tier just takes the cyclops and does not need a seamoth.
Includes an anti parasite module that will pulse the shield (if equipped) at low power to remove leaches.

[CyclopsBioReactor.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927037/CyclopsBioReactor.zip)
`Cyclops BioReactor (SN1)` Makes a small bioreactor you can build inside the cyclops that allows you to use bio energy in the cyclops. Works great with the aquarium overflow mod that is also in `📁mod-download-mirrors`

[CyclopsEngineUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927038/CyclopsEngineUpgrades.zip)
`Cyclops Engine Upgrades (SN1)` makes new tiers of the engine efficiency upgrade each offering increased efficiency.
Higher tiers even reduce energy usage from sonar and shield.

[CyclopsEnhancedSonar.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927039/CyclopsEnhancedSonar.zip)
`Cyclops Enhanced Sonar (SN1)` Adds a topographical map of the area around you similar to the seaglide.
Adding a second module makes the sonar ping faster.

[CyclopsNuclearUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927040/CyclopsNuclearUpgrades.zip)
`Cyclops Nuclear Upgrades (SN1)` makes an upgrade module that acts as a nuclear battery.
Holds 6,000 charge before being depleted, if it is used consistently it must cool down for a while before being able to be used again.

[CyclopsSimpleSolar.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927041/CyclopsSimpleSolar.zip)
`Cyclops Simple Solar (SN1)` makes one simple solar charger that just works as a cyclops version of the seamoth solar charger.

[CyclopsSolarUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927042/CyclopsSolarUpgrades.zip)
`Cyclops Solar Upgrades (SN1)` makes two solar charging upgrades for the cyclops, one is same as seamoth, the other has a built in battery.
Can stack up to six modules to increase charging rate.

[CyclopsSpeedUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927043/CyclopsSpeedUpgrades.zip)
`Cyclops Speed Upgrades (SN1)` Makes upgrade modules that increase the speed of the cyclops at the cost of engine efficiency.
Can stack up to six modules for maximum speed.

[CyclopsThermalUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927044/CyclopsThermalUpgrades.zip)
`Cyclops Thermal Upgrades (SN1)` makes a tier 2 thermal upgrade for the cyclops which includes a built in battery for the upgrade module.
Can stack up to six modules to increase charging rate.

[DataBoxScannerFix.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927045/DataBoxScannerFix.zip)
`DataBox Scanner Fix (SN1)` makes the scanner room not target already collected databoxes.

[IonCubeGenerator.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927046/IonCubeGenerator.zip)
`Ion Cube Generator (SN1)` lets you build a medium sized structure that makes an ion cube every once in a while. about the size of in base bioreactor.
Can be configured to drain base energy faster or slower.

[MoreCyclopsUpgrades.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927047/MoreCyclopsUpgrades.zip)
`More Cyclops Upgrades (SN1)` is primarily if not exclusively an api for other cyclops upgrade mods.
By default, includes a buildable upgrade console for the cyclops for additional upgrade slots (this can be disabled in the config).

[UpgradedVehicles.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927049/UpgradedVehicles.zip)
`Upgraded Vehicles (SN1)` Gives the depth upgrade modules for the seamoth and prawn suit additional effects, 
improving the vehicle's armor, speed, and engine efficiency.

[VehicleUpgradesInCyclops.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927050/VehicleUpgradesInCyclops.zip)
`Vehicle Upgrades In Cyclops (SN1)` Makes the cyclops upgrade fabricator also work as a moonpool vehicle upgrade console. lets you make seamoth and prawn upgrades.
Include includes the vanilla crafts from the moonpool.

# Subnautica Below Zero Mods by PrimeSonic
[UnSlowSeaTruck.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927055/UnSlowSeaTruck.zip)
`UnSlow SeaTruck (BZ)` makes the seatruck unslow by reducing the speed penalty incurred by attaching extra modules on it

[DataBoxScannerFix.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/6927056/DataBoxScannerFix.zip)
`DataBox Scanner Fix (BZ)` makes the scanner room not target already collected databoxes

### CODE REVIEW

**Comment by NagareHisui** [comment]
quick question. Will you archive the rest of your mods? Like the more seamoth depth, seamoth drill arms, seamoth thermal and seamoth arms? Also why were they removed from nexus?

**Comment by PrimeSonic** [comment]
@NagareHisui 
> quick question. Will you archive the rest of your mods? Like the more seamoth depth, seamoth drill arms, seamoth thermal and seamoth arms? Also why were they removed from nexus?

Yes, the other removed mods are being mirrored.
The ones you mentioned are on [Mr Purple's GitHub](https://github.com/MrPurple6411/Subnautica-Mods/releases/tag/0.0.0-Nexus-Removal)

I would suggest checking out the `#mod-download-mirrors` channel on the [Subnautica Modding Discord](https://discord.gg/UpWuWwq) since that's where other links will be found.

**Comment by NagareHisui** [comment]
> @NagareHisui
> 
> > quick question. Will you archive the rest of your mods? Like the more seamoth depth, seamoth drill arms, seamoth thermal and seamoth arms? Also why were they removed from nexus?
> 
> Yes, the other removed mods are being mirrored.
> The ones you mentioned are on [Mr Purple's GitHub](https://github.com/MrPurple6411/Subnautica-Mods/releases/tag/0.0.0-Nexus-Removal)
> Reasons for their removal are related to changes being made at Nexus.
> 
> I would suggest checking out the `#mod-download-mirrors` channel on the [Subnautica Modding Discord](https://discord.gg/UpWuWwq) since that's where other links will be found.

Alright thank you!

**Comment by Zemogiter** [comment]
I can't compile the source code without `GameDir.targets` file

**Comment by PrimeSonic** [comment]
> 
> 
> I can't compile the source code without `GameDir.targets` file
> 


You need to make your own based on where your game installations are.
Just create a new xml/text file named `gameDir.targets` in the root of the repo.

This is what mine looks like. You can start with this as a base and replace the file paths with the ones on your machine.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <SubnauticaDir>D:\SteamApps\steamapps\common\Subnautica</SubnauticaDir>
    <BelowZeroDir>D:\SteamApps\steamapps\common\SubnauticaZero</BelowZeroDir>
    <SubnauticaManagedDir>$(SubnauticaDir)\Subnautica_Data\Managed</SubnauticaManagedDir>
    <BelowZeroManagedDir>$(BelowZeroDir)\SubnauticaZero_Data\Managed</BelowZeroManagedDir>
  </PropertyGroup>
</Project>
```

**Comment by Zemogiter** [comment]
Should I put the content of `<SubnauticaDir>` and `<BelowZeroDir>` in `""` if there are spaces in the path?

**Comment by TheGuyisHere** [comment]
Bless you Sir.

**Comment by BlueSeaAndDragon** [comment]
Do you still support the update of these Mods? I made an error when reading these Mods in the latest version of the gam
[qmodmanager_log-Subnautica.txt](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/8383250/qmodmanager_log-Subnautica.txt)
e

**Comment by PrimeSonic** [comment]
> Do you still support the update of these Mods? I made an error when reading these Mods in the latest version of the gam [qmodmanager_log-Subnautica.txt](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/8383250/qmodmanager_log-Subnautica.txt) e

There are help channels on the [Subnautica Modding Discord](https://discord.gg/UpWuWwq), where you can get technical help if your mods aren't working as expected.

Im not active myself, but for 99% of issues, any active modder can help diagnose and fix them.
You'll find help there.

**Comment by TheGuyisHere** [comment]
> Do you still support the update of these Mods? I made an error when reading these Mods in the latest version of the gam [qmodmanager_log-Subnautica.txt](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/8383250/qmodmanager_log-Subnautica.txt) e

I could probably help you install, I was going to make a how to video to Install all the PrimeSonic Mods and what they do for that matter. But got to busy playing. Lol

**Comment by BlueSeaAndDragon** [comment]
> > 你还支持这些Mod的更新吗？ 我在最新版本的 gam  [qmodmanager_log-Subnautica.txt ](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/8383250/qmodmanager_log-Subnautica.txt)和
> 
> 上有帮助频道， [Subnautica Modding Discord ](https://discord.gg/UpWuWwq)如果您的模组无法按预期工作，您可以在其中获得技术帮助。
> 
> 我自己并不活跃，但对于 99% 的问题，任何活跃的改装者都可以帮助诊断和修复它们。 你会在那里找到帮助。

Thank you for your answer

**Comment by BlueSeaAndDragon** [comment]
> > Do you still support the update of these Mods? I made an error when reading these Mods in the latest version of the gam [qmodmanager_log-Subnautica.txt](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/8383250/qmodmanager_log-Subnautica.txt) e
> 
> There are help channels on the [Subnautica Modding Discord](https://discord.gg/UpWuWwq), where you can get technical help if your mods aren't working as expected.
> 
> Im not active myself, but for 99% of issues, any active modder can help diagnose and fix them. You'll find help there.

Thank you for your answer

**Comment by Giovannyr000** [comment]
Will these mods be updated to the 2.0 version of Subnautica?

**Comment by PrimeSonic** [comment]
> Will these mods be updated to the 2.0 version of Subnautica?

The two mods made in collaboration with FCStudios will be taken over by @ccgould

All others will given to @MrPurple6411 to maintain as needed on his own terms and schedule

**Pull request merged**
