### PR TITLE
Placeable custom batteries & powercells

### PR DESCRIPTION
**Pull request by K07H**
Hopefully it does not need to replace:
CraftDataHandler.SetEquipmentType(this.TechType, this.ChargerType);
with:
CraftDataHandler.SetEquipmentType(this.TechType, EquipmentType.Hand);

### CODE REVIEW

**Review by PrimeSonic — APPROVED** [review]
Since the `EquipmentType` isn't being changed, this should still work normally.  
If we find any weird behavior in testing, we can easily make this a configurable option.

**Comment by K07H** [comment]
"Since the EquipmentType isn't being changed, this should still work normally." Yeah but you might have to drag-n-drop the battery in the quickslot manually since it's not of type Hand.
And if we set it to type Hand, we then have the same thing but for chargers where you need to drag-n-drop the battery in the charger manually.
Someone needs to give it a try to see how it interacts with quickslots like this.

**Comment by K07H** [comment]
"If we find any weird behavior in testing, we can easily make this a configurable option."
True, a simple checkbox should be enough but might require game restart.

**Comment by K07H** [comment]
I did some tests and I'm affraid the "CraftDataHandler.SetEquipmentType(this.TechType, EquipmentType.Hand);" is required in the end, otherwise it won't bind to quickslots properly.
I propose the following solution since I already do the required harmony patches in Decorations mod (I even fixed the drag-n-drop remaining issue now, see v1.9.1 of Deco Mod published 1 hour ago):

Check for Decorations Mod presence. If it is present, simply set equipment type to Hand and Decorations mod will handle the rest, otherwise, let the equipment type to BatteryCharger or PowerCellCharger.
I can prepare the IQMod call that will check if Deco mod is here, enabled, loaded and the reflection bit to get the "EnablePlaceBatteries" feature state so that you can set EquipmentType easily.

**Comment by K07H** [comment]
Ok done.
Maybe it requires "LoadAfter: [ "DecorationsMod" ]" in mod.json since I get the state of "enable placing batteries/powercells" feature from Decorations mod. Not sure.

**Review by PrimeSonic — APPROVED** [review]
I'm okay with these changes.  
Further optimization and caching can be done after this merge.

@MrPurple6411 please chime on this and on https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/pull/122 so we know if we can merge and move forward.

**Review by MrPurple6411 — APPROVED** [review]
Works nicely.

**Pull request merged**
