### PR TITLE
CustomCraft2 ~ New Feature: Modified Foods

### PR DESCRIPTION
**Pull request by PrimeSonic**
Adds a new entry type `ModifiedFoods` for changing the `Food` and `Water` values of existing Eatable items.
_Currently defaults all modified foods to not decompose._

---

[CustomCraft2SML_1-11-0_SN1.zip](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/files/9592626/CustomCraft2SML_1-11-0_SN1.zip)
built from [275d102](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/pull/143/commits/275d102ebf4818442e0fbcc7af2e45f9aa44f160)

### CODE REVIEW

**Comment by Nagorogan** [comment]
is the unityengine.coremodule.dll file intended to be included in the zip file? I can't really see why it would be included there.
image

**Comment by Nagorogan** [comment]
is there supposed to be a modified foods sample file in the sample files folder? Cause if so I'm not seeing one.

**Comment by PrimeSonic** [comment]
> is the unityengine.coremodule.dll file intended to be included in the zip file? I can't really see why it would be included there. image

It was not. Will fix.

**Comment by PrimeSonic** [comment]
> is there supposed to be a modified foods sample file in the sample files folder? Cause if so I'm not seeing one.

There should be. Will add.

**Comment by Nagorogan** [comment]
other than those two, seems to work. Will test a tiny bit more to make sure, but I can't see it encountering any other problems.

**Review by EldritchCarMaker — DISMISSED** [review]
seems all good from what I can tell

**Review by EldritchCarMaker — APPROVED** [review]
only thing I could possibly see being added for now would be comments in the two new sample file, but it's also very self explanatory and simple so I can't see it being an issue in the slightest.

**Pull request merged**
