### PR TITLE
Custom Craft 2 SML- Version 1.5 Update -  Alias Recipes

### PR DESCRIPTION
**Pull request by PrimeSonic**
For more details, view the original Pull Requests #37 | #39

Allows the ability to create multiple recipes that result in the same item without conflicts.

Using the rudimentary Dummy Item Pattern, it is now possible to fully replicate simple crafting mods like Alchemy and Unpack Ingots entirely within CC2.

### CODE REVIEW

**Comment by PrimeSonic** [comment]
@Fdiwen Finally have reports coming in from users testing the beta version.  
Things are looking good. With any luck, in a few days this could be going live (officially).

Since most of my modding attention is still on other projects, let me know if there's any last minute changes you think are worth doing.

You have Push access to the repo, so if you want to just push another branch directly here and create a Pull Request into the `CC2_AliasRecipes` branch, you're free to do so.

**Comment by Fdiwen** [comment]
I've been a bit busy over the past week or two and haven't been playing as much.  The change is working great when I get a chance to play however.  I'm comfortable with the release when you are.

**Comment by PrimeSonic** [comment]
When you have a chance, I would ask if you can write 2 or 3 lines for the ChangeLog on Nexus.

**Comment by Fdiwen** [comment]
Create brand new items in Subnautica and the recipes required to build them.
This enables the ability for multiple recipes to produce the same item.

How about these two lines?  Seems like an okay summary.

**Comment by PrimeSonic** [comment]
> Create brand new items in Subnautica and the recipes required to build them.
> This enables the ability for multiple recipes to produce the same item.
> 
> How about these two lines? Seems like an okay summary.
Looks good. Might also be worth mentioning (if this is really true) that modded items can now appear in CC2 created recipes.

And while you're at it, go ahead and give this merge request one final review.  
If everything looks to be in order, you can approve the changes here on GitHub

This actually all got me thinking and I plan on taking a little time tonight (or tomorrow) to create my own CC2 mod to release along side the v1.5 update as an additional showcasing of what the new version of capable of.
If it all works out like I think it will, I will be making the official release on Nexus tomorrow (Saturday).

**Comment by PrimeSonic** [comment]
After d8bde2a, I have no more doubt that CC2 can now safely handle modded items.

@Fdiwen please review the final changes.

**Comment by Fdiwen** [comment]
Only one minor change - revert a path change to the test csproj file.

**Comment by PrimeSonic** [comment]
Tested the new features. Everything looks good. Over here.

**Comment by Fdiwen** [comment]
Doh - sorry.  I though I had made an inadvertent commit.  All good.

**Comment by PrimeSonic** [comment]
Screw it. I'm awake enough. I might as well go ahead and get this out now.  
Will be updating on Nexus tonight.

**Pull request merged**
