### PR TITLE
Update AuxCyUpgradeConsole.cs

### PR DESCRIPTION
**Pull request by K07H**
I know it's not yet made for Below Zero but I just wanted to show you how I would port this to BZ.
(PS: You would still have to make the regular changes concerning the recipe, from TechData to RecipeData).

### CODE REVIEW

**Comment by K07H** [comment]
Obviously I did not test this (since it will not compile), also I'm not sure about the
constructible.allowedUnderwater = false;
since a Cyclops IS underwater, so this will obviously require some testing.

**Comment by K07H** [comment]
Since I have a formatted prefab DB available for BZ I also added the new resource path for Below Zero ;)

**Comment by K07H** [comment]
This can be merged safely since all the code is inside "#if BELOWZERO" macros.

**Comment by PrimeSonic** [comment]
MoreCyclopsUpgrades is not going to be ported to Below Zero since there is no Cyclops in Below Zero.

**Pull request closed without merging**
