### PR TITLE
Isolate SMLHelper

### PR DESCRIPTION
**Pull request by Fdiwen**
This basically converts the ITechTyped to a string rather than going to a TechType immediately. This does change the parsing to just keep a list of objects rather than a dictionary by TechType. Then, a pre-pass is added to the CustomCraft/ReaderWriter interaction. This resolves the TechType and adds in the case of AliasRecipes. Since we now have TechType, we can still filter out the duplicates - albeit a bit later in the process.

### CODE REVIEW

**Comment by PrimeSonic** [comment]
Pre-Release Beta Test ready to be shared, though probably needs more instructions to help users understand the new structures.
  https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/releases/tag/CC2_Alias

**Comment by PrimeSonic** [comment]
Since I may finally be able to make some time to test this over the weekend,  
if you have additional test files with alias recipes, go ahead and add them to the [CustomCraftSML/SampleFiles](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/tree/master/CustomCraftSML/SampleFiles) folder.

I keep an extra set of sample files for testing even if they aren't part of the release package.  
There's already a few in there, but more test data is never a bad thing.

**Comment by PrimeSonic** [comment]
I'm positive that there won't be any issue for Unpack Ingots. I collaborate with @AlexejheroYTB often enough to know this much.  
For Alchemy, we can ask the author on Nexus if they're cool with there being a modified copy here.

So let's at least add the Unpack Ingot files to serve only as test data. These files won't ever be put on Nexus.  
You can (and should) include info about the original mod in a comment at the top of the file.

**Comment by Fdiwen** [comment]
@AlexejheroYTB The code is all part of the mod.  The actual implementation of the mod is in this one sample file [here](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/CC2_AliasRecipes/CustomCraftSML/SampleFiles/AliasRecipe_UnpackIngots).  Advantages - they both do the same thing really.  This allows for less technical modders to create items and recipes without knowing C#.

**Comment by Fdiwen** [comment]
@PrimeSonic More samples added - alchemy and unpack ingots (credit due the respective creators for the ideas).

**Comment by PrimeSonic** [comment]
Thanks! Over the weekend I'll be able to start testing some of this myself.
The [beta test release](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/releases/tag/CC2_Alias) has been shared on the Subnautica Modding Discord server.  
After I get a chance to try it out myself, I will make it available on Nexus for further beta testing.

> @PrimeSonic More samples added - alchemy and unpack ingots (credit due the respective creators for the ideas).

**Comment by PrimeSonic** [comment]
image
Testing was successful. The Unpack Ingots sample file worked.

**Pull request merged**
