### PR TITLE
Simplified AddCustomModels() function + Textures handling suggestion

### PR DESCRIPTION
**Pull request by K07H**

### CODE REVIEW

**Review by K07H — COMMENTED** [review]
Wait a minute... There is no SetTexture on Renderer? xD

**Comment by K07H** [comment]
Ah the SetTexture() is on Material, wasn't paying attention, so the simplification works.

**Comment by K07H** [comment]
As for the texture replacement it would be better if we can set illum and spec too for better visuals.
Something like this:
`internal abstract class CbCore : ModPrefab
{
	internal static Dictionary<TechType, Tuple<Texture2D, Texture2D, Texture2D>> BatteryModels { get; } = new Dictionary<TechType, Tuple<Texture2D, Texture2D, Texture2D>>();
	internal static Dictionary<TechType, Tuple<Texture2D, Texture2D, Texture2D>> PowerCellModels { get; } = new Dictionary<TechType, Tuple<Texture2D, Texture2D, Texture2D>>();
	...
	
internal static class EnergyMixinPatcher
{
	private static void AddCustomModels(GameObject originalModel, ref List<BatteryModels> Models, Dictionary<TechType, Tuple<Texture2D, Texture2D, Texture2D>> customModels)
	{
		foreach (KeyValuePair<TechType, Tuple<Texture2D, Texture2D, Texture2D>> pair in customModels)
		{
			GameObject obj = GameObject.Instantiate(originalModel, originalModel.transform.parent);
			obj.name = pair.Key.AsString() + "_model";

			Renderer renderer = obj.GetComponentInChildren<Renderer>();
			if (renderer != null)
			{
				renderer.material.SetTexture(ShaderPropertyID._MainTex, pair.Value.Item1);
				renderer.material.SetTexture(ShaderPropertyID._Illum, pair.Value.Item2);
				renderer.material.SetTexture(ShaderPropertyID._SpecTex, pair.Value.Item3);
			}
			
			Models.Add(new BatteryModels() { model = obj, techType = pair.Key });
		}
	}
	...`

**Comment by K07H** [comment]
Where:
* Item1 (Texture2D) => main texture.
* Item2 (Texture2D) => illum texture (or null if you don't want illum).
* Item3 (float) => illum strength (or negative value if you don't want illum), it's generally a value between 0 and 1 but you can give a value higher than 1 for saturated illumination.
* Item4 (Texture2D) => specular texture (or null if you don't want specular effect).

**Review by PrimeSonic — APPROVED** [review]
Regarding this: https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/pull/122#issuecomment-706825809

I would consider leaving this for a later revision.  
We would come back and see about making a new API or class that is better designed for all the extra texture maps we would need to handle.

**Review by MrPurple6411 — APPROVED** [review]
Works... just missed 1 spot

**Comment by K07H** [comment]
"I would consider leaving this for a later revision."
Well I guess MrPurple could not wait :p

**Pull request merged**
